name: store-sales
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy=1.26
  - pandas=2.3
  - matplotlib=3.10
  - scikit-learn=1.8
  - lightgbm=4.6
  - jupyter
  - pip
  - pip:
      - neuralforecast==3.1.9
